apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
spec:
  selector:
    matchLabels:
      app: k8s-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: k8s-demo
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management
        imagePullPolicy: Never
